language: ruby
sudo: false
rvm:
  - 2.4.1
env:
  - RAILS_VERSION="~> 5.1.0"
matrix:
  exclude: # Rails 5 is incompatible with Ruby < 2.2.2
    - rvm: 1.9.3
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 2.0.0
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 2.1.10
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 1.9.3
      env: RAILS_VERSION="~> 5.1.0"
    - rvm: 2.0.0
      env: RAILS_VERSION="~> 5.1.0"
    - rvm: 2.1.10
      env: RAILS_VERSION="~> 5.1.0"
  fast_finish: true
before_script:
  - "[ $TRAVIS_RUBY_VERSION = \"1.9.3\" ] && travis_retry gem install mime-types --version \"~> 2\" || true"
  - "[ $TRAVIS_RUBY_VERSION = \"1.9.3\" -o $TRAVIS_RUBY_VERSION = \"2.0.0\" ] && travis_retry gem install nokogiri --version \"~> 1.6.8\" || true"
  - travis_retry gem install rails --version "$RAILS_VERSION"
script: bundle exec ruby -I test test/acceptance_test.rb -n '/basic/'
